[package]
name = "ptt-crawler-rs"
version = "0.1.0"
authors = ["CYBAI <cyb.ai.815@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
select = "0.4.2"
serde = "1.0.58"
serde_json = "1.0.17"
regex = "1.0.0"
rocket = "0.3.11"
rocket_codegen = "0.3.11"
serde_derive = "1.0.59"
